### ISSUE TITLE
the app crashes when calling Activity.finish() because of the library

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [lopspower/CircularImageView#109]
version used 3.2.0

the issue is present in stack over flow by another user as well :
https://stackoverflow.com/questions/56200896/unable-to-destroy-activity-failed-to-call-observer-method

when you call Activity.finish(), the app crashes and these are the logs that holds the root cause :

Caused by: kotlin.UninitializedPropertyAccessException: lateinit property initialState has not been initialized
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.access$getInitialState$p(CircularProgressButton.kt:21)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton$morphAnimator$2.invoke(CircularProgressButton.kt:70)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton$morphAnimator$2.invoke(CircularProgressButton.kt:21)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.getMorphAnimator(Unknown Source:7)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.dispose(CircularProgressButton.kt:171)
at java.lang.reflect.Method.invoke(Native Method)
at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316) 
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334) 
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123) 
at androidx.lifecycle.ReportFragment.onDestroy(ReportFragment.java:108) 
at android.app.Fragment.performDestroy(Fragment.java:2870) 
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1424) 
at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1554) 
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1616) 
at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3044) 
at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3024) 
at android.app.FragmentController.dispatchDestroy(FragmentController.java:244) 
at android.app.Activity.performDestroy(Activity.java:7251) 
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249) 
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4492) 
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523) 
at android.app.ActivityThread.-wrap5(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:176) 
at android.app.ActivityThread.main(ActivityThread.java:6701) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by lopspower** [comment]
The stack says the problem is from another library:
`br.com.simplepass.loadingbutton.customViews.CircularProgressButton` and no `CircularImageView`.

**Comment by Ahmed-Adel-Ismail** [comment]
Sorry
