### ISSUE TITLE
On setting a drawable or image to android:src it gives java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by virenbisht** [lopspower/CircularImageView#127]
Hi, On setting image to src i get render errors on my android studio preview tab.
A screenshot on the error is given below.

![Screenshot (98)](https://user-images.githubusercontent.com/67057578/84900804-3a858c80-b0c8-11ea-9af2-b836b2fd6958.png)

Upon searching i found this bitmap class file.

![Screenshot (99)](https://user-images.githubusercontent.com/67057578/84900926-67d23a80-b0c8-11ea-9be9-5af5efeb4552.png)

Here is the full stacktrace:
`java.lang.IllegalArgumentException: can't create bitmap without a color space
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1119)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:952)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:807)
	at com.mikhaellopez.circularimageview.CircularImageView.bitmapDrawableToBitmap(CircularImageView.kt:452)
	at com.mikhaellopez.circularimageview.CircularImageView.drawableToBitmap(CircularImageView.kt:430)
	at com.mikhaellopez.circularimageview.CircularImageView.loadBitmap(CircularImageView.kt:329)
	at com.mikhaellopez.circularimageview.CircularImageView.onDraw_Original(CircularImageView.kt:222)
	at com.mikhaellopez.circularimageview.CircularImageView.onDraw(CircularImageView.kt)
	at android.view.View.draw_Original(View.java:21443)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$9(RenderTask.java:819)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by virenbisht** [comment]
Also, I am using android studio 3.6.1 and build files or components belong to androidx.
