### ISSUE TITLE
Bug: cannot view in IDE "preview" or UI-editor modes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [lopspower/CircularImageView#38]
At least show the content as if it's the normal imageView, to see how the bounds work.

**Comment by lopspower** [comment]
It's a very good point. I tried several times to offer an overview but I did not happen.
I need help with this !! Is what you can watch that @AndroidDeveloperLB ?

**Comment by AndroidDeveloperLB** [comment]
I don't understand the question, but you can use "isInEditMode()" to identify that the view is shown on the IDE instead of on a real device/emulator.

**Comment by Zapnologica** [comment]
I am having similar problem:

If I go to design view in android studio for the layout , I get the following:

```
java.lang.NoClassDefFoundError: android/media/ThumbnailUtils
	at com.mikhaellopez.circularimageview.CircularImageView.updateShader(CircularImageView.java:170)
	at com.mikhaellopez.circularimageview.CircularImageView.loadBitmap(CircularImageView.java:145)
	at com.mikhaellopez.circularimageview.CircularImageView.onDraw_Original(CircularImageView.java:120)
	at com.mikhaellopez.circularimageview.CircularImageView.onDraw(CircularImageView.java)
	at android.view.View.draw(View.java:16178)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16181)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:431)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:428)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:362)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
	at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$6.run(AndroidDesignerEditorPanel.java:480)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by lopspower** [comment]
Please show [issue 42](https://github.com/lopspower/CircularImageView/issues/42)

**Comment by AndroidDeveloperLB** [comment]
@lopspower Again, if you wish to overcome this, you can use "isInEditMode" and do anything you wish there that should work specifically in the UI editor of Android-Studio.
At the very least, show nothing, so that it won't cause errors.

**Comment by lopspower** [comment]
Yes today I have the solution. I'll commit and deploy today :).
Thank you @AndroidDeveloperLB

**Comment by AndroidDeveloperLB** [comment]
@lopspower Thank you for this nice library. If you wish, you can check out mine too:
https://github.com/AndroidDeveloperLB?tab=repositories
