### ISSUE TITLE
am getting render error

### ISSUE THREAD

**Issue by firaskudsy** [lopspower/CircularImageView#42]
am getting the following error 

Failed to find style 'circularImageViewStyle' in current theme

when i run the app i see the circularimageview, but on design i get the above error

**Comment by MELAS007** [comment]
Dear Lopez,

Kindly solve this issue ASAP!

I can't use your CircularImageView!

Regards,
Marwan

**Comment by acoard** [comment]
I believe I'm getting this error too.  Here's a full stack trace.  Any help would be appreciated.

    java.lang.NoClassDefFoundError: android/media/ThumbnailUtils
	at com.mikhaellopez.circularimageview.CircularImageView.updateShader(CircularImageView.java:170)
	at com.mikhaellopez.circularimageview.CircularImageView.loadBitmap(CircularImageView.java:145)
	at com.mikhaellopez.circularimageview.CircularImageView.onDraw_Original(CircularImageView.java:120)
	at com.mikhaellopez.circularimageview.CircularImageView.onDraw(CircularImageView.java)
	at android.view.View.draw(View.java:16178)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16181)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:431)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:428)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:362)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
	at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$6.run(AndroidDesignerEditorPanel.java:480)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)

**Comment by acoard** [comment]
I found this thread: http://stackoverflow.com/questions/5321853/java-lang-noclassdeffounderror-android-media-thumbnailutils

My app definitely targets above API 8, however it looks like this library doesn't. Could that be the issue?

**Comment by DarkNormal** [comment]
**+1 for this issue**
I've been using this library for a while and it's great, but it would be even better if it allowed for the preview of the view in Android Studio.

**Comment by Rainer-Lang** [comment]
+1

**Comment by lopspower** [comment]
I fix this bug with the new release 3.0.0:
`compile 'com.mikhaellopez:circularimageview:3.0.0'`
